sinks:
  out:
    inputs:
      - "my_source_id"
    type: "console"
    encoding:
      codec: "text"
  my_sink_id:
    type: file
    inputs:
      - my_source_id
    path: /tmp/agent-%Y-%m-%d.log
    # compression: gzip
    max_file_size_bytes: 52428800
    compression: none
    encoding:
      codec: json
  sqlite_output:
    type: sqlite
    inputs:
      - my_source_id
    path: /tmp/scx_agent-%Y-%m-%d.db
    table: "events"
    idle_timeout_secs: 300
    encoding:
      codec: json
    timezone: local
sources:
  my_source_id:
    type: host_metrics
    cpu:
      metrics:
        - "cpu_softirq_all"
        - "cpu_softirq_block_total"
        - "cpu_softirq_hi_total"