# SQLite Sink 配置示例
# 将事件写入SQLite数据库

sinks:
  sqlite_output:
    type: sqlite
    inputs: ["my-source-or-transform"]

    # 数据库文件路径
    path: "/tmp/events.db"

    # 表名
    table: "events"

    # 空闲超时时间（秒）
    idle_timeout_secs: 300

    # 编码配置
    encoding:
      codec: json

    # 时区设置
    timezone: local

    # 示例：使用模板变量
    # path: "/tmp/{{ service_name }}-events.db"
    # table: "{{ log_level }}_events"
